#!/usr/bin/env python3
"""Update opencode_model.md with the current free OpenCode models.

Python 3.8+; standard library only.
Primary source: https://opencode.ai/zen/v1/models
The output is intentionally both human-readable Markdown and BAT-parseable.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

MODELS_URL = "https://opencode.ai/zen/v1/models"
DOCS_URL = "https://opencode.ai/docs/zen"
DEFAULT_MODEL = "muse-spark-1.3-contributor-free"
PROVIDER_PREFIX = "opencode/"

# OpenCode has occasionally offered a zero-cost model whose ID does not include
# the literal word "free". Keep explicit exceptions small and documented.
KNOWN_FREE_EXCEPTIONS = {
    "big-pickle",
}

# Negative guardrails. These are not expected to match current free IDs, but
# prevent accidental inclusion if an upstream naming convention changes.
EXCLUDE_PATTERNS = (
    re.compile(r"(?:^|-)pro(?:-|$)", re.I),
    re.compile(r"(?:^|-)max(?:-|$)", re.I),
)


def http_get_json(url: str, timeout: int = 20) -> Dict:
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "OpenCode-Free-Model-Updater/1.0",
            "Accept": "application/json",
        },
    )
    with urllib.request.urlopen(req, timeout=timeout) as response:
        raw = response.read()
    return json.loads(raw.decode("utf-8"))


def is_free_model(model_id: str) -> bool:
    mid = model_id.strip().lower()
    if not mid:
        return False
    if any(p.search(mid) for p in EXCLUDE_PATTERNS) and "free" not in mid:
        return False
    return "free" in mid or mid in KNOWN_FREE_EXCEPTIONS


def pretty_name(model_id: str) -> str:
    special = {
        "muse-spark-1.3-contributor-free": "Muse Spark 1.3 Contributor Free",
        "muse-spark-1.2-contributor-free": "Muse Spark 1.2 Contributor Free",
        "mimo-v2.6-flash-free": "MiMo V2.6 Flash Free",
        "mimo-v2.5-free": "MiMo V2.5 Free",
        "deepseek-v4-flash-free": "DeepSeek V4 Flash Free",
        "space-bunny-free": "Space Bunny Free",
        "longcat-2.5-preview-free": "LongCat 2.5 Preview Free",
        "ling-3.0-flash-fin-free": "Ling 3.0 Flash Fin Free",
        "ling-3.1-flash-free": "Ling 3.1 Flash Free",
        "nemotron-3-ultra-free": "Nemotron 3 Ultra Free",
        "nemotron-3.5-lightning-free": "Nemotron 3.5 Lightning Free",
        "jev-1.13-free": "Jev 1.13 Free",
        "fledge-alpha-free": "Fledge Alpha Free",
        "big-pickle": "Big Pickle",
    }
    if model_id in special:
        return special[model_id]
    words = model_id.replace("-", " ").split()
    return " ".join(w.upper() if w in {"ai", "gpt", "glm"} else w.capitalize() for w in words)


def normalize_models(payload: Dict) -> List[str]:
    data = payload.get("data")
    if not isinstance(data, list):
        raise ValueError("Unexpected OpenCode model API response: missing data[]")

    ids: List[str] = []
    seen = set()
    for item in data:
        if not isinstance(item, dict):
            continue
        model_id = str(item.get("id", "")).strip()
        if is_free_model(model_id) and model_id not in seen:
            seen.add(model_id)
            ids.append(model_id)

    if DEFAULT_MODEL in seen:
        ids.remove(DEFAULT_MODEL)
        ids.insert(0, DEFAULT_MODEL)

    return ids


def render_markdown(model_ids: Iterable[str], updated_at: datetime) -> str:
    ids = list(model_ids)
    lines = [
        "# OpenCode Free Models",
        "",
        f"Updated (UTC): {updated_at.astimezone(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        f"Source API: {MODELS_URL}",
        f"Source docs: {DOCS_URL}",
        "",
        "This file is generated by `update_opencode_models.py`.",
        "The launcher parses only table rows beginning with `| M |`.",
        "Do not change that marker if you want `opencode_launcher.bat` to read the file.",
        "",
        "## Free models",
        "",
        "| Type | Display name | OpenCode model ID | Default |",
        "|---|---|---|---|",
    ]

    for model_id in ids:
        full_id = PROVIDER_PREFIX + model_id
        default = "YES" if model_id == DEFAULT_MODEL else ""
        lines.append(f"| M | {pretty_name(model_id)} | `{full_id}` | {default} |")

    lines += [
        "",
        "## Notes",
        "",
        "- `Enter` in the BAT model menu selects Muse Spark 1.3 Contributor Free when available.",
        "- The updater keeps only model IDs advertised by the OpenCode model endpoint and classified as free by ID/known official free exceptions.",
        "- If the web update fails, keep the last known good Markdown file; the BAT launcher can continue using it.",
        "",
    ]
    return "\n".join(lines)


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8", newline="\n")
    tmp.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser(description="Update OpenCode free-model Markdown list")
    parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().with_name("opencode_model.md")),
        help="Output Markdown file",
    )
    parser.add_argument("--timeout", type=int, default=20, help="HTTP timeout in seconds")
    args = parser.parse_args()

    output = Path(args.output).expanduser().resolve()
    try:
        payload = http_get_json(MODELS_URL, timeout=max(5, args.timeout))
        model_ids = normalize_models(payload)
        if not model_ids:
            raise RuntimeError("No free models were detected; refusing to overwrite the last known good file")

        markdown = render_markdown(model_ids, datetime.now(timezone.utc))
        atomic_write(output, markdown)
        print(f"[OK] Updated: {output}")
        print(f"[OK] Free models: {len(model_ids)}")
        for i, model_id in enumerate(model_ids, 1):
            marker = " [DEFAULT]" if model_id == DEFAULT_MODEL else ""
            print(f"  {i:>2}. {PROVIDER_PREFIX}{model_id}{marker}")
        return 0
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, json.JSONDecodeError, ValueError, RuntimeError, OSError) as exc:
        print(f"[ERROR] Model update failed: {exc}", file=sys.stderr)
        print("[INFO] Existing opencode_model.md was not overwritten.", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
